<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Application Settings -->
		<OutputType>WinExe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>guard.ico</ApplicationIcon>
		<RootNamespace>Guard</RootNamespace>
		<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>AnyCPU;x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>

		<!-- Assembly & Product Metadata (Required for Signing) -->
		<Company>Aleksei Skorobogatko</Company>
		<Product>Guard for Windows</Product>
		<Copyright>Copyright © Aleksei Skorobogatko 2025</Copyright>
		<Version>1.0.0.0</Version>
		<!-- Sets both Assembly and File Version -->

		<!-- Descriptive Metadata -->
		<Title>Guard for Windows</Title>
		<Description>Guard is a Windows application designed to provide robust, scheduled filtering of internet content. It uses a combination of hosts file modifications and Windows Firewall rules to enforce restrictions based on user-defined rules and categories.</Description>

		<!-- NuGet Package & Repository Info -->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/ganjie/Guard.alexweb.app_client</RepositoryUrl>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/ganjie/Guard.alexweb.app_client</PackageProjectUrl>
		<PackageIcon>android-chrome-192x192.png</PackageIcon>
	</PropertyGroup>

  <ItemGroup>
    <Content Include="guard.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Downloads\android-chrome-192x192.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="D:\000_Work\0001\C-sharp\guard\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="D:\000_Work\0001\C-sharp\guard\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Guard.Core\Guard.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.DirectoryServices" />
    <Reference Include="System.Messaging" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceProcess" />
    <Reference Include="UIAutomationClient" />
    <Reference Include="UIAutomationTypes" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AssignForm.cs" />
    <Compile Remove="AssignForm.Designer.cs" />
    <Compile Remove="PairingForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
