using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Guard.Contracts.Relay;
using Guard.Protocol.Relay;
using Guard.Windows.Cryptography;

namespace Guard.Windows.RelayCrypto.Tests;

// Public test keys only. This generator never reads enrollment, OS state or production keys.
internal static class InteropExchange
{
    private const string RecipientPrivate = "317f915db7bc629c48fe765587897e01e282d3e8445f79f27f65d031a88082b2";
    private const string RecipientPublic = "04abc7e49a4c6b3566d77d0304addc6ed0e98512ffccf505e6a8e3eb25c685136f853148544876de76c0f2ef99cdc3a05ccf5ded7860c7c021238f9e2073d2356c";
    private static readonly DateTimeOffset Now = new(2026, 7, 24, 12, 0, 0, TimeSpan.Zero);

    public static void Export(string path)
    {
        using var device = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        using var parent = ECDsa.Create(Parameters(Hex(RecipientPublic), Hex(RecipientPrivate)));
        var snapshot = new RequestSnapshot("device-alpha-0001", 2, 4, "event-alpha-000001", "request-alpha-001", 3,
            RelayTargetKind.Website, "https://example.test/path", new[] { new RelayEvidenceField("host", "example.test") },
            "homework", Now.AddMinutes(-1), Now.AddHours(2), Enumerable.Range(1, 32).Select(x => (byte)x).ToArray(), 9);
        var request = new DeviceSignedRequestEnvelope(snapshot, "device-signing-0001", new byte[64]);
        request = new DeviceSignedRequestEnvelope(snapshot, request.DeviceKeyId, device.SignHash(RelayCanonicalEncoding.ComputeDeviceRequestHash(request)));
        var approval = new SignedApprovalEnvelope(4, "parent-key-alpha1", 1, "command-alpha-001", "nonce-alpha-00001", Now, Now.AddMinutes(5),
            snapshot.DeviceId, 2, snapshot.RequestId, 3, RelayCanonicalEncoding.ComputeRequestSnapshotHash(snapshot), snapshot.GetDecisionChallengeCopy(),
            snapshot.TargetKind, snapshot.CanonicalTargetIdentity, 9, ParentDecisionKind.AllowTemporary, 60, new byte[64]);
        var approvalBytes = RelayCanonicalEncoding.EncodeApprovalForSignature(approval);
        var receipt = new CommandReceipt(snapshot.DeviceId, 2, 4, approval.KeyId, 1, approval.CommandId, snapshot.RequestId, 3,
            CommandReceiptStatus.AcceptedPendingReconciliation, Now.AddSeconds(1), SHA256.HashData(approvalBytes), 10,
            ReconciliationStatus.Pending, "policy-committed-0001");
        var signedReceipt = new DeviceSignedCommandReceiptEnvelope(receipt, request.DeviceKeyId, new byte[64]);
        signedReceipt = new DeviceSignedCommandReceiptEnvelope(receipt, request.DeviceKeyId, device.SignHash(RelayCanonicalEncoding.ComputeDeviceReceiptHash(signedReceipt)));
        var plainRequest = RelayCanonicalEncoding.EncodeDeviceRequestEnvelope(request);
        var plainReceipt = RelayCanonicalEncoding.EncodeDeviceReceiptEnvelope(signedReceipt);
        var applied = new CommandReceipt(snapshot.DeviceId, 2, 4, approval.KeyId, 1, approval.CommandId, snapshot.RequestId, 3,
            CommandReceiptStatus.Applied, Now.AddSeconds(2), SHA256.HashData(approvalBytes), 10, ReconciliationStatus.Reconciled, "policy-applied-00001");
        var signedApplied = new DeviceSignedCommandReceiptEnvelope(applied, request.DeviceKeyId, new byte[64]);
        signedApplied = new DeviceSignedCommandReceiptEnvelope(applied, request.DeviceKeyId, device.SignHash(RelayCanonicalEncoding.ComputeDeviceReceiptHash(signedApplied)));
        var plainApplied = RelayCanonicalEncoding.EncodeDeviceReceiptEnvelope(signedApplied);
        var values = new Dictionary<string, string>
        {
            ["recipient.private"] = RecipientPrivate,
            ["recipient.public"] = RecipientPublic,
            ["device.public"] = Convert.ToHexString(Serialize(device.ExportParameters(false).Q)),
            ["now"] = Now.ToUnixTimeMilliseconds().ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["request.plaintext"] = Convert.ToHexString(plainRequest),
            ["request.frame"] = Convert.ToHexString(Seal(RelayFrameKind.Request, plainRequest, 1)),
            ["receipt.plaintext"] = Convert.ToHexString(plainReceipt),
            ["receipt.frame"] = Convert.ToHexString(Seal(RelayFrameKind.Receipt, plainReceipt, 2)),
            ["applied.plaintext"] = Convert.ToHexString(plainApplied),
            ["applied.frame"] = Convert.ToHexString(Seal(RelayFrameKind.Receipt, plainApplied, 3)),
            ["approval.input"] = Convert.ToHexString(approvalBytes),
            ["approval.signature"] = Convert.ToHexString(parent.SignData(approvalBytes, HashAlgorithmName.SHA256))
        };
        File.WriteAllLines(path, new[] { "# PUBLIC TEST MATERIAL ONLY - generated by Guard.Windows.RelayCrypto.Tests --export-interop" }
            .Concat(values.Select(x => x.Key + "=" + x.Value)), new UTF8Encoding(false));
        Console.WriteLine("Exported public interop test vector.");
    }

    public static void VerifyFixture()
    {
        var values = Load();
        using var device = ECDsa.Create(Parameters(Hex(values["device.public"])));
        foreach (var name in new[] { "request", "receipt", "applied" })
        {
            var frame = RelayCanonicalEncoding.DecodeRelayFrame(Hex(values[name + ".frame"]));
            var aad = RelayCanonicalEncoding.EncodeRelayFrameAssociatedData(frame);
            var plaintext = RelayCryptography.Decrypt(Hex(values["recipient.private"]), Hex(values["recipient.public"]),
                frame.GetEncapsulatedKeyCopy(), frame.GetCiphertextCopy(), aad, Info(frame.Kind, aad));
            Require(plaintext.SequenceEqual(Hex(values[name + ".plaintext"])));
            if (name == "request")
            {
                var signed = RelayCanonicalEncoding.DecodeDeviceRequestEnvelope(plaintext);
                Require(device.VerifyHash(RelayCanonicalEncoding.ComputeDeviceRequestHash(signed), signed.GetSignatureP1363Copy()));
            }
            else
            {
                var signed = RelayCanonicalEncoding.DecodeDeviceReceiptEnvelope(plaintext);
                Require(device.VerifyHash(RelayCanonicalEncoding.ComputeDeviceReceiptHash(signed), signed.GetSignatureP1363Copy()));
            }
        }
    }

    public static void VerifyAndroid(string path)
    {
        var values = Load();
        var approval = RelayCanonicalEncoding.DecodeApprovalEnvelope(Hex(File.ReadAllText(path).Trim()));
        using var parent = ECDsa.Create(Parameters(Hex(values["recipient.public"])));
        Require(parent.VerifyHash(RelayCanonicalEncoding.ComputeApprovalHash(approval), approval.GetSignatureP1363Copy()));
        Require(RelayCanonicalEncoding.EncodeApprovalForSignature(approval).SequenceEqual(Hex(values["approval.input"])));
        Console.WriteLine("PASS Android approval signature and exact request binding verified by .NET.");
    }

    private static byte[] Seal(RelayFrameKind kind, byte[] plaintext, long cursor)
    {
        RelayFrame Frame(byte[] enc, byte[] cipher) => new(kind, "mailbox-alpha-0001", "recipient-key-0001", "frame-alpha-00000" + cursor,
            cursor, 0, Now.AddMinutes(-1), Now.AddHours(1), enc, cipher);
        var aad = RelayCanonicalEncoding.EncodeRelayFrameAssociatedData(Frame(Array.Empty<byte>(), Array.Empty<byte>()));
        var ciphertext = RelayCryptography.Encrypt(Hex(RecipientPublic), plaintext, aad, Info(kind, aad), out var encapsulated);
        return RelayCanonicalEncoding.EncodeRelayFrame(Frame(encapsulated, ciphertext));
    }

    private static byte[] Info(RelayFrameKind kind, byte[] aad) => Encoding.ASCII.GetBytes(kind == RelayFrameKind.Request
        ? "guard-relay-request-hpke-v1" : "guard-relay-receipt-hpke-v1").Concat(aad).ToArray();
    private static Dictionary<string, string> Load() => File.ReadAllLines(Path.Combine(AppContext.BaseDirectory, "relay-exchange-v1.properties"))
        .Where(x => !string.IsNullOrWhiteSpace(x) && !x.StartsWith('#')).Select(x => x.Split('=', 2)).ToDictionary(x => x[0], x => x[1]);
    private static byte[] Hex(string value) => Convert.FromHexString(value);
    private static ECParameters Parameters(byte[] key, byte[]? d = null) => new() { Curve = ECCurve.NamedCurves.nistP256,
        Q = new ECPoint { X = key[1..33], Y = key[33..65] }, D = d };
    private static byte[] Serialize(ECPoint point) => new byte[] { 4 }.Concat(point.X!).Concat(point.Y!).ToArray();
    private static void Require(bool condition) { if (!condition) throw new InvalidOperationException("Interop mismatch."); }
}
